### ISSUE TITLE
catch httpx.ConnectError

### ISSUE THREAD

**Issue by tykling** [tykling/dns_exporter#80]
```
2024-02-16 04:34:35 +0000 dns_exporter.__main__ INFO DNSExporter.main():117:  dns_exporter v0.2.1.dev3+ga5e6563.d20230412 starting up - logging at level INFO
2024-02-16 05:14:00 +0000 dns_exporter.dns_exporter.exporter ERROR DNSExporter.do_GET():846:  Got an exception while looking up qname unicast.censurfridns.dk using server SplitResult(scheme='https', netloc='rgnet-iad.anycast.censurfridns.dk', path='/dns-query', query='', fragment='')
Traceback (most recent call last):
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/dns/query.py", line 123, in connect_tcp
    raise httpcore.ConnectError
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/home/tykling/dns_exporter/src/dns_exporter/exporter.py", line 828, in do_GET
    r, transport = self.get_dns_response(
  File "/usr/home/tykling/dns_exporter/src/dns_exporter/exporter.py", line 524, in get_dns_response
    r = dns.query.https(
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/dns/query.py", line 484, in https
    response = session.post(url, headers=headers, content=wire, timeout=timeout)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/home/tykling/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
2024-02-16 05:14:00 +0000 dns_exporter.dns_exporter.exporter WARNING DNSExporter.do_GET():850:  query failure, returning other_failure

```

**Comment by tykling** [comment]
89ac05e6211eb8d5bf66b62acf7c41ce14c1332e
